source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/expo/expo.git'

require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/expo/scripts/autolinking'

platform :ios, '15.1'

use_frameworks! :linkage => :static
use_modular_headers!

target 'SRG' do
  use_react_native!(:path => "../node_modules/react-native")
  use_expo_modules!
end

post_install do |installer|
  react_native_post_install(
    installer,
    File.join(installer.sandbox_root, '../node_modules/react-native'),
    :mac_catalyst_enabled => false,
    :ccache_enabled => false
  )
end
