// Quirky game news snippets for preloaders
export const GAME_NEWS_QUIPS = [
  "Did you know? The new Call of Duty update just dropped! 🎮",
  "Breaking: Elden Ring DLC is finally here! ⚔️",
  "Hot take: Baldur's Gate 3 just won Game of the Year! 🏆",
  "PSA: Cyberpunk 2077 is actually good now! 🚀",
  "News flash: The Legend of Zelda: Tears of the Kingdom is incredible! 🗡️",
  "Did you see? Final Fantasy XVI has epic boss battles! 💫",
  "FYI: Starfield just launched with 1000+ planets! 🌌",
  "Update: Hogwarts Legacy sold 15 million copies! 🧙",
  "Breaking: Resident Evil 4 Remake is terrifyingly good! 🧟",
  "Hot news: God of War Ragnarök won multiple awards! ⚡",
  "Did you know? The Last of Us Part II is getting a remaster! 🎬",
  "Update: Spider-Man 2 is swinging into action! 🕷️",
  "News: Alan Wake 2 is a mind-bending masterpiece! 🔦",
  "FYI: Diablo IV Season 2 is live! 👹",
  "Breaking: Assassin's Creed Mirage is back to basics! 🗡️",
  "Did you see? Mortal Kombat 1 has insane fatalities! 💀",
  "Update: Street Fighter 6 is fighting strong! 👊",
  "News: Super Mario Bros. Wonder is pure joy! 🍄",
  "Hot take: Lies of P is the best Souls-like this year! 🤖",
  "PSA: Armored Core VI is mech combat perfection! 🤖",
  "Fun fact: Some gamers have played Skyrim for over 10,000 hours! 🐉",
  "Did you hear? A speedrunner beat Elden Ring in under 20 minutes! ⚡",
  "Wild: Someone built a working computer in Minecraft! 🎮",
  "Crazy: The Witcher 3 has over 100 hours of content! 🗡️",
  "Mind-blowing: Tetris was used to treat PTSD! 🧩",
  "Interesting: Pac-Man was originally called Puck-Man! 👻",
  "Cool fact: The first video game was created in 1958! 🕹️",
  "Amazing: Minecraft has sold over 300 million copies! ⛏️",
  "Wow: Some players have been playing World of Warcraft since 2004! 🐉",
  "Epic: The longest gaming session lasted 138 hours! 🎮",
  "Insane: A gamer spent $1 million on virtual items! 💰",
  "Legendary: Someone beat Dark Souls using a dance pad! 💃",
  "Unbelievable: A cat accidentally speedran a game! 🐱",
  "Shocking: Gaming is now bigger than movies and music combined! 🎬",
  "Incredible: The average gamer is 35 years old! 📊",
  "Fascinating: Esports players can earn millions! 💸",
  "Remarkable: Gaming improves hand-eye coordination! 👁️",
  "Awesome: Some games have over 1000 endings! 🎯",
  "Phenomenal: Gaming can reduce stress by 68%! 😌",
  "Spectacular: The gaming industry is worth $200 billion! 💎",
  "Marvelous: Some gamers have photographic memory! 🧠",
  "Stunning: Virtual reality can trick your brain! 🥽",
  "Astounding: Gaming communities have raised millions for charity! ❤️",
  "Extraordinary: Some games take 10+ years to develop! ⏰",
  "Magnificent: Gaming can improve problem-solving skills! 🧩",
  "Wonderful: The first esports tournament was in 1972! 🏆",
  "Fantastic: Some games have procedurally generated universes! 🌌",
  "Incredible: Gaming can help with depression and anxiety! 💙",
  "Amazing: Some players have perfect pitch from rhythm games! 🎵",
];

// Get a random game news quip
export function getRandomGameNews(): string {
  return GAME_NEWS_QUIPS[Math.floor(Math.random() * GAME_NEWS_QUIPS.length)];
}
